import { motion } from 'framer-motion';
import Navbar from './components/navbar.js'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import Card from './components/card.js'

var gymjam_desc = "A web app dedicated to commenting on how full the gyms on UChicago campus are. Leave a comment denoting the level of fullness, if basketball hoops are available, and any other things worth mentioning."
var shuffle_desc = "A web app simulating shuffling a hand of five cards. Click shuffle to generate a hand, and search through previous shuffles to find a match!"
var scribble_desc = "A tranquil collaborative canvas where you can scribble to your hearts content. Use arrow keys to move, and spacebar to save the image! Have your friends join in to watch the sockets at work!"
var art_desc = "A VR art gallery hosting pieces generated by machine learning models. Explore the 3d space to see art displayed in a way impossible in real life."
export default function proj(){
  return(
    <div style={{backgroundColor: "white", height: "100vh"}}>
        <Navbar color="black"/>
        <div className={styles.projlayout}>
        <div className={styles.projectstitle} style={{marginTop: "25px"}}>
        My projects
        </div>
            <div className={styles.cardrow} style={{marginTop: "50px"}}>
                <Card
                link="https://gymjam.vercel.app/"
                color="red"
                info="Gymjam"
                image="/gymjam.png"
                tag="NextJS | MongoDB"
                description={gymjam_desc}
                favicon="/gymfav.png"
                date_started="2019"
                hoster="Hosted on Vercel"/>
                <Card
                link="https://shuffle-site.herokuapp.com/"
                color="orange"
                info="Shuffle-O"
                image="/shuffle.png"
                tag="ReactJS | Firebase"
                description={shuffle_desc}
                favicon="/shuffavi.png"
                date_started="2018"
                hoster="Hosted on Heroku"/>
                <Card
                link="https://thoranderskow.github.io/final/"
                color="tan"
                info="VR Art Gallery"
                image="/final.png"
                tag="A-frame | Javascript"
                description={art_desc}
                favicon="/artfavi.png"
                date_started="2021"
                hoster="Hosted on Github Pages"/>
                <Card
                link="http://scribbledayz.herokuapp.com/"
                color="gray"
                info="Scribbledayz"
                image="/scribdays.png"
                tag="p5.js | socket.io"
                description={scribble_desc}
                favicon="/scribfavi.png"
                date_started="2021"
                hoster="Hosted on Heroku"/>
            </div>
        </div>
        <style global jsx>{`
       html,
      body,
      body > div:first-child,
      div#__next,
      div#__next > div {
        height: 100%;
      }

             `}
        </style>
    </div>
  )
}
